name: real-estate

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn install
        working-directory: scraper
      - run: yarn lint
        working-directory: scraper

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn install
        working-directory: scraper
      - run: yarn test
        working-directory: scraper

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        uses: hashicorp/setup-terraform@v1

      - name: format
        run: terraform fmt -check
