name: real-estate

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn install
        working-directory: scraper
      - run: yarn lint
        working-directory: scraper
